### ISSUE TITLE
Using BehaviorSubject when not needed

### ISSUE THREAD

**Issue by justinwoo** [oscarduignan/koa-react-router-rxjs-example#1]
This is something I messed up a lot until I learned the operator also exists in RxJS, but you should probably use `Rx.Observable.just(value)` if you just need a cold stream with a value in it.

https://github.com/oscarduignan/koa-react-router-rxjs-example/blob/master/model.js#L5

```
var a = new Rx.BehaviorSubject(defaults.a || 1);
```

could become

```
var a = Rx.Observable.just(defaults.a || 1);
```

**Comment by oscarduignan** [comment]
Hey Justin, you're right, I think here I was coding with future bits in my mind. Here's an example of that kind of line of thinking that I was on https://github.com/oscarduignan/react-rxjs-elasticsearch-faceted-search-example/blob/master/src/js/search/observables.factory.js - it's a bit different to the gist I posted a little while back (older than it) but it shows the idea of wrapping the model in a function and letting you pass in default starting values via it's params (though I think i might pass in intent streams rather than default values in future iterations as it seems more "reactive") so that you could have multiple simultaneous models (which it turns out is what you need when rendering on the server since node modules get cached - not so much of an issue in the browser unless you want to display the thing in different places)
